# Generated by Django 5.0.3 on 2024-03-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'My Custom User Profile'},
        ),
    ]
