# Generated by Django 5.0.3 on 2024-03-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
