# Generated by Django 5.0.3 on 2024-03-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_profile',
        ),
    ]
